// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqellorkzgnbijkpyelf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xZWxsb3JremduYmlqa3B5ZWxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NzQ4MjksImV4cCI6MjA2NDQ1MDgyOX0.WVFrxgBJCx93kfKwMEeJ2jMLc9gVaJevPhftjM87MiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);