import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea'; // Keep for potential future direct use, or remove if strictly not needed
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'; // Keep for potential future direct use
// Removed Card imports to achieve a minimalist layout
// import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
// Dialog related imports are now handled by TaskSuggestionFormModal
import { PlusCircle, Edit2, Trash2 } from 'lucide-react';
import { useToast } from "@/hooks/use-toast";
import TaskSuggestionFormModal from './TaskSuggestionFormModal'; // Import the new modal

export interface TaskSuggestion {
  id: string;
  name: string; // Display name for the suggestion in the list
  title?: string; // Pre-filled task title
  description?: string;
  priority?: 'low' | 'medium' | 'high';
  location?: string;
  quantity?: number;
  unit?: string;
  // Add other relevant fields from the Task interface if needed
}

export const STORAGE_KEY = 'ratTracker_taskSuggestions'; // Export STORAGE_KEY

const TaskSuggestionSettings = () => {
  const [suggestions, setSuggestions] = useState<TaskSuggestion[]>([]);
  const [isModalOpen, setIsModalOpen] = useState(false); // This is the correct state variable
  const [editingSuggestion, setEditingSuggestion] = useState<TaskSuggestion | null>(null);
  // const [currentSuggestion, setCurrentSuggestion] = useState<Partial<TaskSuggestion>>({}); // This was correctly removed as it's in the form modal
  const { toast } = useToast();

  // Helper function defined inside the component to access `toast`
  const saveSuggestionsToLocalStorage = (updatedSuggestions: TaskSuggestion[]): boolean => {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(updatedSuggestions));
      return true;
    } catch (error) {
      console.error("Failed to save suggestions to localStorage:", error);
      toast({
        title: "Storage Error",
        description: "Could not save suggestions. Your browser's local storage might be full or unavailable.",
        variant: "destructive",
      });
      return false;
    }
  };

  useEffect(() => {
    const storedSuggestions = localStorage.getItem(STORAGE_KEY);
    if (storedSuggestions) {
      setSuggestions(JSON.parse(storedSuggestions));
    } else {
      // Seed with default suggestions if localStorage is empty
      const defaultTaskSuggestions: TaskSuggestion[] = [
        { id: 'default-1', name: "Cage Cleaning", title: "Perform cage cleaning", priority: 'medium' },
        { id: 'default-2', name: "Vet Appointment", title: "Vet Appointment for [Rat Name]", priority: 'high' },
        { id: 'default-3', name: "Bedding Restock", title: "Restock bedding supplies", priority: 'low' },
        { id: 'default-4', name: "Food Restock", title: "Restock rat food", priority: 'medium' },
        { id: 'default-5', name: "Water Refill", title: "Refill water bottles", priority: 'medium' },
        { id: 'default-6', name: "Playtime", title: "Schedule playtime", priority: 'low' },
      ];
      setSuggestions(defaultTaskSuggestions);
      localStorage.setItem(STORAGE_KEY, JSON.stringify(defaultTaskSuggestions));
    }
  }, []);

  // const saveSuggestions = (updatedSuggestions: TaskSuggestion[]) => { // This function will be removed
  //   setSuggestions(updatedSuggestions);
  //   localStorage.setItem(STORAGE_KEY, JSON.stringify(updatedSuggestions));
  // };

  const openFormModal = (suggestionToEdit: TaskSuggestion | null = null) => {
    setEditingSuggestion(suggestionToEdit);
    setIsModalOpen(true); // Use setIsModalOpen
  };

  const closeFormModal = () => {
    setIsModalOpen(false); // Use setIsModalOpen
    setEditingSuggestion(null); // Clear editing state when modal closes
  };

  // Input change handlers are removed as they are now in TaskSuggestionFormModal

  const handleSaveSuggestion = (suggestionToSave: TaskSuggestion) => {
    let newSuggestionsList: TaskSuggestion[];
    const isEditing = suggestions.some(s => s.id === suggestionToSave.id);

    if (isEditing) {
      newSuggestionsList = suggestions.map(s =>
        s.id === suggestionToSave.id ? suggestionToSave : s
      );
    } else {
      // For a truly new suggestion, the ID should have been generated by the form modal
      // or we ensure it's unique here if it wasn't.
      // The form modal now handles ID generation for new items.
      newSuggestionsList = [...suggestions, suggestionToSave];
    }

    if (saveSuggestionsToLocalStorage(newSuggestionsList)) {
      setSuggestions(newSuggestionsList);
      toast({ title: "Success", description: `Suggestion ${isEditing ? 'updated' : 'added'}.` });
      closeFormModal();
    }
  };

  const handleDeleteSuggestion = (id: string) => {
    const newSuggestionsList = suggestions.filter(s => s.id !== id);
    if (saveSuggestionsToLocalStorage(newSuggestionsList)) {
      setSuggestions(newSuggestionsList);
      toast({ title: "Success", description: "Suggestion deleted." });
    }
  };

  return (
    <div className="relative p-4"> {/* Use a div instead of Card for more control */}
      {/* Add button positioned absolutely in the top right corner */}
      <div className="absolute top-4 right-4">
        <Button onClick={() => openFormModal()} variant="ghost" size="icon" title="Add new suggestion">
          <PlusCircle className="h-6 w-6 text-gray-600 hover:text-gray-800" /> {/* Larger icon, subtle color */}
        </Button>
      </div>

      {suggestions.length === 0 ? (
        <p className="text-sm text-gray-500 text-center py-8">No quick suggestions yet. Click '+' to add one.</p>
      ) : (
        <ul className="space-y-3 mt-12"> {/* Add top margin to account for the absolute button */}
          {suggestions.map(suggestion => (
            <li key={suggestion.id} className="p-3 border rounded-lg flex justify-between items-center bg-white shadow-sm"> {/* Subtle shadow */}
              <div>
                <p className="font-semibold text-gray-800">{suggestion.name}</p>
                <p className="text-xs text-gray-500">
                  {suggestion.title ? `Title: ${suggestion.title}` : 'No pre-filled title'}
                  {suggestion.priority && `, Priority: ${suggestion.priority.charAt(0).toUpperCase() + suggestion.priority.slice(1)}`} {/* Capitalize priority */}
                </p>
              </div>
              <div className="space-x-2">
                <Button variant="ghost" size="icon" onClick={() => openFormModal(suggestion)} title="Edit suggestion">
                  <Edit2 className="h-4 w-4 text-gray-500 hover:text-gray-700" />
                </Button>
                <Button variant="ghost" size="icon" onClick={() => handleDeleteSuggestion(suggestion.id)} title="Delete suggestion">
                  <Trash2 className="h-4 w-4 text-red-500 hover:text-red-700" />
                </Button>
              </div>
            </li>
          ))}
        </ul>
      )}

      <TaskSuggestionFormModal
        isOpen={isModalOpen}
        onOpenChange={setIsModalOpen}
        editingSuggestion={editingSuggestion}
        onSave={handleSaveSuggestion}
      />
    </div>
  );
};

export default TaskSuggestionSettings;